export const DATABASE_CONNECTION: string = 'DATABASE_CONNECTION';
export const REGION_REPOSITORY: string = 'REGION_REPOSITORY';
export const CITY_REPOSITORY: string = 'CITY_REPOSITORY';
export const USER_REPOSITORY: string = 'USER_REPOSITORY';
export const EMPLOYEE_REPOSITORY: string = 'EMPLOYEE_REPOSITORY';
export const ACCOUNT_REPOSITORY: string = 'ACCOUNT_REPOSITORY';
export const ACCOUNT_TYPE_REPOSITORY: string = 'ACCOUNT_TYPE_REPOSITORY';